/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kode_project;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author riand
 */
public class allQuiz extends javax.swing.JFrame {

    /**
     * Creates new form allQuiz
     */
    int absen = 99;
    String QuizID = " ";

    public allQuiz(int absen) {
        this.absen = absen;
        initComponents();
        displayTabel(absen);
        buttonOff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuiz = new javax.swing.JTable();
        StopBut = new javax.swing.JButton();
        StartBut = new javax.swing.JButton();
        CopyBut = new javax.swing.JButton();
        viewScoreBut = new javax.swing.JButton();
        viewJoinBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1440, 760));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(14, 31, 52));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("All Quiz");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(633, 17, -1, -1));

        jPanel1.setBackground(new java.awt.Color(10, 14, 24));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1184, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 230, 1184, 570));

        jButton1.setBackground(new java.awt.Color(25, 48, 78));
        jButton1.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 150, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 100));

        jPanel3.setBackground(new java.awt.Color(10, 14, 24));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableQuiz.setBackground(new java.awt.Color(25, 48, 78));
        tableQuiz.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        tableQuiz.setForeground(new java.awt.Color(255, 255, 255));
        tableQuiz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quiz ID", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuiz.setToolTipText("");
        tableQuiz.setSelectionBackground(new java.awt.Color(25, 39, 95));
        tableQuiz.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tableQuiz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableQuizMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableQuiz);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 1253, 503));

        StopBut.setBackground(new java.awt.Color(25, 48, 78));
        StopBut.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        StopBut.setForeground(new java.awt.Color(255, 255, 255));
        StopBut.setText("STOP");
        StopBut.setToolTipText("to stop quiz");
        StopBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButActionPerformed(evt);
            }
        });
        jPanel3.add(StopBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 100, 40));

        StartBut.setBackground(new java.awt.Color(25, 48, 78));
        StartBut.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        StartBut.setForeground(new java.awt.Color(255, 255, 255));
        StartBut.setText("START");
        StartBut.setToolTipText("to start quiz");
        StartBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButActionPerformed(evt);
            }
        });
        jPanel3.add(StartBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 100, 40));

        CopyBut.setBackground(new java.awt.Color(25, 48, 78));
        CopyBut.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        CopyBut.setForeground(new java.awt.Color(255, 255, 255));
        CopyBut.setText("Copy ID");
        CopyBut.setToolTipText("to stop quiz");
        CopyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyButActionPerformed(evt);
            }
        });
        jPanel3.add(CopyBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, 40));

        viewScoreBut.setBackground(new java.awt.Color(25, 48, 78));
        viewScoreBut.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        viewScoreBut.setForeground(new java.awt.Color(255, 255, 255));
        viewScoreBut.setText("View Score");
        viewScoreBut.setToolTipText("to stop quiz");
        viewScoreBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewScoreButButActionPerformed(evt);
            }
        });
        jPanel3.add(viewScoreBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 120, 40));

        viewJoinBut.setBackground(new java.awt.Color(25, 48, 78));
        viewJoinBut.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        viewJoinBut.setForeground(new java.awt.Color(255, 255, 255));
        viewJoinBut.setText("View Join");
        viewJoinBut.setToolTipText("to stop quiz");
        viewJoinBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewJoinButButActionPerformed(evt);
            }
        });
        jPanel3.add(viewJoinBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 120, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1440, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayTabel(int absen) {
        try {
            String sql = "SELECT * FROM quizid WHERE user_id = ?";
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            PreparedStatement psmt = conn.prepareStatement(sql);
            psmt.setInt(1, absen);
            ResultSet rs = psmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tableQuiz.getModel();
            model.setRowCount(0);

            String started = "Stoped";
            while (rs.next()) {
                if (rs.getBoolean("started")) {
                    started = "Started";
                }

                Object[] data = {
                    rs.getString("QuizID"),
                    started
                };

                model.addRow(data);
            }
            tableQuiz.setModel(model);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
    }

    public void startStopQuiz(String id, boolean started) {
        try {
            String sql = "UPDATE quizid SET started = ? WHERE QuizID = ?";
            java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
            PreparedStatement psmt = conn.prepareStatement(sql);
            psmt.setBoolean(1, started);
            psmt.setString(2, id);
            psmt.execute();
            displayTabel(absen);

            String status = " ";
            if (started) {
                status = "mulai";
            } else {
                status = "hentikan";
            }
            JOptionPane.showConfirmDialog(this, "Quiz berhasil di " + status + "!", "Succes", JOptionPane.OK_OPTION);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, e);
        }
    }

    private static void copyToClipboard(String text) {
        StringSelection selection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, null);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new dash_admin(absen).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

   private void buttonOn(){
       viewScoreBut.setVisible(true);
       StartBut.setEnabled(true);
       StopBut.setEnabled(true);
       CopyBut.setEnabled(true);
   }
    
   private void buttonOff(){
       viewScoreBut.setVisible(false);
       StartBut.setEnabled(false);
       StopBut.setEnabled(false);
        CopyBut.setEnabled(false);
   }
   
    private void StartButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Yakin me-mulai Quiz :" + QuizID + "?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
        if (a == 0) {
            startStopQuiz(QuizID, true);
        }

    }//GEN-LAST:event_StartButActionPerformed

    private void StopButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButActionPerformed
        int a = JOptionPane.showConfirmDialog(this, "Yakin me-hentikan Quiz :" + QuizID + "?", "Confirm", JOptionPane.OK_CANCEL_OPTION);
        if (a == 0) {
            startStopQuiz(QuizID, false);
        }

    }//GEN-LAST:event_StopButActionPerformed

    private void tableQuizMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQuizMousePressed
       DefaultTableModel model = (DefaultTableModel) tableQuiz.getModel();
       
       int selectedIndex = tableQuiz.getSelectedRow();
       
       if (selectedIndex >= 0){
           String id =  model.getValueAt(selectedIndex, 0).toString();
           
           QuizID = id;
           buttonOn();
       }
    }//GEN-LAST:event_tableQuizMousePressed

    private void CopyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyButActionPerformed
        copyToClipboard(QuizID);
        JOptionPane.showMessageDialog(this, "Succes!, Copy code to clipboard!");
    }//GEN-LAST:event_CopyButActionPerformed

    private void viewScoreButButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewScoreButButActionPerformed
       new admin_cekScore(QuizID, absen).setVisible(true);
    }//GEN-LAST:event_viewScoreButButActionPerformed

    private void viewJoinButButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewJoinButButActionPerformed
       new joinLogs(QuizID).setVisible(true);
    }//GEN-LAST:event_viewJoinButButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allQuiz(99).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CopyBut;
    private javax.swing.JButton StartBut;
    private javax.swing.JButton StopBut;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableQuiz;
    private javax.swing.JButton viewJoinBut;
    private javax.swing.JButton viewScoreBut;
    // End of variables declaration//GEN-END:variables
}
